# Generated by Django 3.1.3 on 2021-03-10 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_raspdevice_lastactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Starting', 'Starting'), ('Stopped', 'Stopped'), ('Yawning', 'Yawning'), ('Drowsiness', 'Drowsiness'), ('MissingFace', 'MissingFace')], max_length=50)),
                ('timeOccured', models.DateTimeField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('isRead', models.BooleanField(blank=True, null=True)),
                ('devices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.raspdevice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('timeOccured',), name='time'),
        ),
    ]
