# Generated by Django 3.1.3 on 2021-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='isRead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
