# Generated by Django 3.1.3 on 2021-07-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_alert_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='detect',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Drowsiness', 'Drowsiness')], max_length=50),
        ),
    ]
