# Generated by Django 3.1.3 on 2021-03-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_alert_drive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='devices',
            new_name='device',
        ),
    ]
