# Generated by Django 3.1.3 on 2021-07-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_auto_20210713_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='detect',
            field=models.CharField(choices=[('Noeye', 'Noeye'), ('Drowsiness', 'Drowsiness'), ('Alcohol', 'Alcohol')], max_length=50),
        ),
        migrations.AlterField(
            model_name='drive',
            name='status',
            field=models.CharField(choices=[(1, 'ongoing'), (0, 'ended')], max_length=20),
        ),
    ]
