# Generated by Django 3.1.3 on 2021-04-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_raspdevice_lastactive'),
        ('realtime', '0003_auto_20210313_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastActive', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.raspdevice')),
            ],
        ),
    ]
