# Generated by Django 3.1.3 on 2021-04-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_activecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecheck',
            name='lastActive',
        ),
        migrations.AddField(
            model_name='activecheck',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='activecheck',
            constraint=models.UniqueConstraint(fields=('time',), name='timeActive'),
        ),
    ]
