# Generated by Django 3.1.3 on 2021-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_auto_20210728_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='detect',
            field=models.CharField(choices=[('Noeye', 'Không thấy khuôn mặt'), ('Drowsiness', 'Không tỉnh táo'), ('Alcohol', 'Đồ uống có cồn')], max_length=50),
        ),
    ]
