# Generated by Django 3.1.3 on 2021-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_auto_20210728_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('ended', 'ended')], max_length=20),
        ),
    ]
