# Generated by Django 3.1.3 on 2021-05-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210506_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspdevice',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.car'),
        ),
    ]
