# Generated by Django 3.1.3 on 2021-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_roomcode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('licensePlate',), name='licensePlate'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name',), name='name'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('roomCode',), name='roomCode'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('licenseDriver',), name='licenseDriver'),
        ),
    ]
