# Generated by Django 3.1.3 on 2021-06-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210510_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspdevice',
            name='ipaddress',
        ),
        migrations.AddField(
            model_name='raspdevice',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
