# Generated by Django 3.1.3 on 2021-03-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_raspdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspdevice',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.car'),
        ),
    ]
