# Generated by Django 3.1.3 on 2021-06-22 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210617_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='raspdevice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddConstraint(
            model_name='raspdevice',
            constraint=models.UniqueConstraint(fields=('password',), name='password'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
