# Generated by Django 3.1.3 on 2021-03-08 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210307_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspdevice',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.car'),
        ),
    ]
