# Generated by Django 3.1.3 on 2021-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210308_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspdevice',
            name='lastActive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
