# Generated by Django 3.1.3 on 2021-04-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_raspdevice_lastactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspdevice',
            name='lastActive',
        ),
    ]
