# Generated by Django 3.1.3 on 2021-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210413_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspdevice',
            name='websocketID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
