# Generated by Django 3.1.3 on 2021-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_raspdevice_websocketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspdevice',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
