# Generated by Django 3.1.3 on 2021-01-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210120_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timeOccured',
            field=models.DateTimeField(null=True),
        ),
    ]
