# Generated by Django 3.1.3 on 2021-01-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210121_1100'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('timeOccured',), name='time'),
        ),
    ]
