# Generated by Django 3.1.3 on 2021-01-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210122_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrydevice',
            name='lastActive',
            field=models.DateTimeField(null=True),
        ),
    ]
