# Generated by Django 3.1.3 on 2021-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_raspberrydevice_lastactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrydevice',
            name='lastActive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
