# Generated by Django 3.1.3 on 2021-02-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210125_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityName',
            field=models.CharField(choices=[('Starting', 'Starting'), ('Stopped', 'Stopped'), ('Yawning', 'Yawning'), ('Drowsiness', 'Drowsiness'), ('MissingFace', 'MissingFace')], max_length=50),
        ),
    ]
