# Generated by Django 3.1.3 on 2021-02-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210201_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('idCard', models.CharField(blank=True, max_length=8, null=True)),
                ('licenseDriver', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
    ]
